# Uncomment this line to define a global platform for your project
# platform :ios, “7.0”

#target “ZYZone” do

platform :ios, '7.0'

pod 'FlurrySDK', '~> 5.3'
pod 'CrashlyticsFramework', '~> 2.2'
pod 'AFNetworking', '~> 2.4.1'
pod 'FXImageView', '~> 1.3'
pod 'MBProgressHUD'
pod 'HMSegmentedControl', '~> 1.4'
pod 'SDWebImage', '~> 3.7'
pod 'MagicalRecord', '~> 2.2'
pod 'FlatUIKit'
pod 'CocoaLumberjack'
pod 'BFKit'
pod 'YTKNetwork', '~> 0.2.0'
pod 'FastImageCache', '~> 1.3'
pod 'Mantle', '~> 1.5.4'
pod 'JSONModel', '~> 1.0.2'
pod 'XHTwitterPaggingViewer', '~> 0.5'
pod 'NYXImagesKit', '~> 2.3'

#end

#target "ZYZoneTests" do

#end

