# Uncomment this line to define a global platform for your project
# platform :ios, “7.0”

#target “ZYZone” do

platform :ios, '7.0'

pod 'FlurrySDK', '~> 5.3'
pod 'CrashlyticsFramework', '~> 2.2'
pod 'AFNetworking', '~> 2.4.1'
pod 'FXImageView', '~> 1.3'
pod 'MBProgressHUD'
pod 'HMSegmentedControl', '~> 1.4'
pod 'SDWebImage', '~> 3.7'
pod 'MagicalRecord', '~> 2.2'
pod 'FlatUIKit'
pod 'CocoaLumberjack'
pod 'BFKit'

#end

#target "ZYZoneTests" do

#end

